### ISSUE TITLE
The readme file seems to reference NIST's SP800-22 implementation

### ISSUE THREAD

**Issue by joshuaehill** [dj-on-github/SP800_90b_tests#10]
The README file suggests that the NIST tool "has a terrible text mode menus, questions and answers user interface". These observations seem to apply to sts (the reference SP800-22 implementation). I don't think that this is true of either the Python or C++ NIST tool.

**Comment by dj-on-github** [comment]
You’re right. The terrible ui is the sp800-22 tool. However usually I have
to test a lot of files collected over many chips at many voltages and
temperatures. Our internal qual criteria are a lot more stringent than
nist’s. The nist 90B tool doesn’t accept multiple files and doesn’t output
CSV. Look at djent for an example of better file handling and output. It
will take a list of filenames, parse the test conditions from the filename
and include that, the filename and test results in csv output, one file per
line that automated scripts can turn into plots that get drop into a
template latex entropy report document.  This 90B python code is hardly
good in that respect but it should be by the time it’s done. I expect to
shift a bunch of code to C for speed but want to get it correct before
making it fast. Of course a couple of certifications is getting in the way
of working on this.

**Comment by dj-on-github** [comment]
I updated the readme to reflect reality a little better.
