### ISSUE TITLE
Verbose flag isn't accepted by (any?) test

### ISSUE THREAD

**Issue by joshuaehill** [dj-on-github/SP800_90b_tests#11]
At present, the tool crashes because the main script tries to pass in verbose=verbose as a parameter. The testing functions don't seem to accept this parameter.

**Comment by dj-on-github** [comment]
Argh. Shouldn't have checked that bit in. They will all take it shortly.

**Comment by dj-on-github** [comment]
They do now. They don't do anything with it yet.

**Comment by dj-on-github** [comment]
Now the verbose flag leads to the verbiosity going to stderr. No flag leads to no verbiosity. --csv gives csv output to stdout and no --csv gives summary format output to stdout.
