### ISSUE TITLE
LZ78Y results mismatch

### ISSUE THREAD

**Issue by joshuaehill** [dj-on-github/SP800_90b_tests#15]
I'm seeing a significant mismatch between this tool and the updated NIST / UL tool in the LZ78Y test. The updated NIST and UL tools agree with each other, but this tool behaves differently.

**Comment by joshuaehill** [comment]
I found the problem. In the event of ties for the predictor, the largest value wasn't selected (this behavior is described in step 3.b.ii). As a note, this tie resolution also applies to the MultiMMC test, so if you pattern the logic for that test after the LZ78Y, you'll need to do the same thing there.

In the file sp800_90b_lz78y.py, the code:
`
 if D[prev][cy] > maxyval:
`

should be changed to:
`
 if D[prev][cy] >= maxyval:
`

**Comment by dj-on-github** [comment]
Thank you. Equality inserted.
