### ISSUE TITLE
LRS estimate outputs seem dubious

### ISSUE THREAD

**Issue by joshuaehill** [dj-on-github/SP800_90b_tests#6]
I'm seeing a significant mismatch in the LRS test results between your 90B implementation and our internal tool. Our internal tool agrees with the NIST python tool (that is, if you update the LRS part of the NIST python tool so that the changes in the final 90B have been applied, then our tool agrees with the updated NIST python tool).

**Comment by dj-on-github** [comment]
Yes. That’s on the list. I’m happy to hear your tool matches NISTs - I know
the mismatch is in my code. I don’t like the answer it produces - large
under estimation of actual entropy.

**Comment by dj-on-github** [comment]
I've found a couple of bugs in my LRS code and got the result to be pretty close to NIST's, but not exactly. I ran the NIST python LRS over the same uniform random file and added a print in the find_u() function and saw this:
u =  1  count= 524432
u =  2  count= 262483
u =  3  count= 131424
u =  4  count= 65867
u =  5  count= 33060
u =  6  count= 16617
u =  7  count= 8380
u =  8  count= 4255
u =  9  count= 2168
u =  10  count= 1107
u =  11  count= 582
u =  12  count= 309
u =  13  count= 171
u =  14  count= 97
u =  15  count= 58
u =  16  count= 39
u =  17  count= 23
u =  18  count= 16
u: 18

The spec says find the smallest u such that the most common u-tuple is less than 35. The answer is clear 17 - which is what my code finds, but the NIST code finds u=18, when u=17 has a count of 23.

So it looks like a bug in the NIST code.

My u search find the same counts and identifies u as 17:
Testing u= 1   max tuple count:  524468  max_tuple= (0,)
   Testing u= 2   max tuple count:  262297  max_tuple= (0, 0)
   Testing u= 3   max tuple count:  131166  max_tuple= (0, 0, 0)
   Testing u= 4   max tuple count:  65924  max_tuple= (1, 0, 0, 0)
   Testing u= 5   max tuple count:  33044  max_tuple= (0, 0, 0, 1, 0)
   Testing u= 6   max tuple count:  16694  max_tuple= (1, 0, 0, 0, 0, 1)
   Testing u= 7   max tuple count:  8487  max_tuple= (0, 1, 0, 0, 0, 0, 1)
   Testing u= 8   max tuple count:  4290  max_tuple= (0, 1, 0, 0, 0, 0, 1, 0)
   Testing u= 9   max tuple count:  2166  max_tuple= (0, 1, 0, 1, 1, 0, 0, 0, 1)
   Testing u= 10   max tuple count:  1125  max_tuple= (1, 0, 0, 0, 1, 0, 0, 1, 1, 1)
   Testing u= 11   max tuple count:  583  max_tuple= (1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1)
   Testing u= 12   max tuple count:  313  max_tuple= (0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0)
   Testing u= 13   max tuple count:  172  max_tuple= (0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1)
   Testing u= 14   max tuple count:  98  max_tuple= (0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0)
   Testing u= 15   max tuple count:  60  max_tuple= (0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0)
   Testing u= 16   max tuple count:  35  max_tuple= (1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1)
   Testing u= 17   max tuple count:  23  max_tuple= (0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0)
    u : 17

I'm uploading my updated code, but I think the NIST python code is wrong.

**Comment by dj-on-github** [comment]
I'm not closing this until it's clear if the bug is in here, in the NIST code or in the NIST spec.

**Comment by joshuaehill** [comment]
Is the data file that you were using for this the "goodmegrand.bin" file (and if so, what symbol size did you use?)

**Comment by joshuaehill** [comment]
To be clear, I hadn't noticed a u/v mismatch between the NIST tool, your tool, and the UL tool in the data files that I was looking at, so that's surely not the only thing going on.

I'm not sure why you're keeping state in the ith_unique_W_tuple_count list. Why not just use tuple_dict.values()?

**Comment by joshuaehill** [comment]
Also, in your search for u/v, why are these values limited to 128? That's going to provide invalid answers with a number of instances (bad sources / long inputs). If you're going to arbitrarily limit the size to this range, you should probably produce an error when the correct u/v values are above 128.

A number of the test cases that I published result in larger u/v values.

**Comment by dj-on-github** [comment]
The nist code is looking for < 20
    # 1. Find the smallest u such that the number of occurrences of the most
    #    common u-tuple in S is less than 20.
    u = find_u(s, 20)
    if verbose:
        print ("u:",u)

The spec says 35:
   "Find the smallest u such that the number of occurrences of the most common u-tuple in S is less than 35."

**Comment by dj-on-github** [comment]
I was using goodmegrand.bin with 1 bit. 
With 8 bit (and a larger file: quickrdrand -k 1024 -b > largerfile.bin) this code and nists agree because the u count descends quicker and jumps over both 35 and 20 in one step.

**Comment by dj-on-github** [comment]
$ ./sp800_90b_tests.py -t lrs gmr8.bin -l 8 -s 1000000
LEN bitlist =  8000000
symbols =  1000000
bitcount =  8000000
  1
LRS Test
   Symbol Length         8
   Number of bits        8000000
   Number of Symbols     1000000
   t-threshold =  35
   Testing u= 1   max tuple count:  4073
   Testing u= 2   max tuple count:  37
   Testing u= 3   max tuple count:  4
    u : 3
   DICT SIZE: 970852
   Testing v= 1   max tuple count:  4073
   Testing v= 2   max tuple count:  37
   Testing v= 3   max tuple count:  4
   Testing v= 4   max tuple count:  2
   Testing v= 5   max tuple count:  1
   DICT SIZE: 999996
    v : 4
   p_hat                 0.00391948278015704
   pu                    0.004080438968574471
   Symbol Min Entropy    7.93705992076934
   Min Entropy per bit   0.9921324900961676
Min Entropy Estimate : H_inf(X) =  0.9921324900961676

**Comment by joshuaehill** [comment]
The change from 20 to 35 is to follow a difference between the 2016 draft and the final document. The version currently on github is against the 2016 draft. NIST has not yet produced a 90B-final version (though they say that they're close...)

**Comment by dj-on-github** [comment]
OK. I'll leave it at 35 to match the final spec - I implemented all these from the final spec.

**Comment by joshuaehill** [comment]
Also, if you're comparing the results with NIST's tool, you should apply the other changes as well. They're well captured in a delta document that NIST produced:
https://csrc.nist.gov/CSRC/media/Publications/sp/800-90b/final/documents/sp800-90B-changes-2nd-draft-to-final-markup.pdf

For most tests, these changes are easy to apply.
