### ISSUE TITLE
Lag prediction estimate issues

### ISSUE THREAD

**Issue by joshuaehill** [dj-on-github/SP800_90b_tests#7]
N appears to be set incorrectly within the Lag prediction estimate (it is supposed to be L-1, but this code sets it to L-63, perhaps borrowing from the MultiMCW predictor.) Indeed, the predictor loop seems to have been borrowed from MultiMCW predictor, and the logic for the existing predictor loop needs to be changed; (I think that all references to the "w" array are erroneous for the Lag predictor).

**Comment by dj-on-github** [comment]
A coding session is in order tonight. Thank you for finding this. The MMC
in the checked in code is messed up and this is related.

**Comment by dj-on-github** [comment]
I've put (hopefully) the right code into the lag prediction test..
